# Config File

# The minimum level of fortune for the auto-smelt to work
# Permission needed: ImmortalCustom.autosmelt
smeltFortune: 4

# The worlds where the fortune/autosmelt isn't active
disabledWorlds:
  - 'world_nether'
  - 'world_the_end'
  - 'world_2'

# Toggle automaticaly pickup blocks
# If the list is on, only blocks in it will be picked
# Permission needed: ImmortalCustom.autopickup
autopickup: true

# The autoupdater for ImmortalCustom
autoupdater:
  enabled: true # Enable or not the autoupdater for ImmortalCustom 
  # If it is disabled, it can still be used manually with /fortune update
  download: true # Whether it should download the plugin when an update is available.
  delay: 900 # The delay, in seconds, between each update check.
  # Set to -1 to make it check only on server startup.
  admins: true # Whether it should warn admins when they login, or when an update is found an update is available
  # Permission needed: ImmortalCustom.autoupdater
  # This will force-check for updates each time a player with permission joins
  url: 'http://au.wc.lt/plugins/ImmortalCustom.jar' # This shouldn't change, but it's the url to the plugin
  # The path to your ImmortalCustom jar file, that will be replaced when downloading an update.
  # Leave this empty for the plugin to guess the path (might not work).
  path: 'plugins/ImmortalCustom.jar'

# If true, flames will appear when a block is smelted
flames: true

# If true, when the player's inventory is full, will drop the items
# Permission needed: ImmortalCustom.dropdown
dropdown: true

# If true, ingots the player receives are crafted to blocks
# Permission needed: ImmortalCustom.orestoblocks
orestoblocks: true

# The multiplier (default is 0.2 = /5)
# If set to 1, fortune 100 will give 100 blocks
# This will then be multiplied by a multiplicator (see below) if needed
multiplier: 0.2

# The maximum loot difference (+/-) 0 = no random
difference: 3

# If not empty, the message sent to the player when his inv is full
fullmessage: '&3[&6ImmortalCustom&3] &2&lYour inventory is full!'

# The message sent when a player tries to build and he doesn't have the permission
nobuild: '&3[&6ImmortalCustom&3] &4Sorry, you cannot build here!'

# If not empty, the text to show the number of blocks broken
# NOTE: If you change this, all the pickaxes already used will be broken
blocksbroken: '&bBlocks Broken: &f{BLOCKS}'

# If the blocks broken are shown or not in the lore
# NOTE: If you change this, all the pickaxes already used will be broken
blocksbrokenlore: true

# If the blocks broken are shown or not in the action bar
# NOTE: You can only use this if you have blocks broken lore active
blocksbrokenactionbar: true

# If not empty, the text to show the number of blocks broken in item name
# NOTE: If you change this, all the pickaxes already used will be broken
blocksbrokenitemname: '&9 [&b{BLOCKS}&9]'

# The message when a player doesn't have permission for a command/action
permission: '&cYou do not have the permissions to use this!'

# The sound played when a player's inventory is full
fullsound: 'BLOCK_NOTE_BASS 10 10'

# The sound played when a player shift right clicks
orestoblocksound: 'ENTITY_PLAYER_BURP 10 10'

# What blocks are "smelted" in what blocks
smelts:
  IRON_ORE: IRON_INGOT
  GOLD_ORE: GOLD_INGOT

# Turn this to true if you want the list down below to be active
pickuplist: false

# The blocks that are picked up
pickupBlocks:
  - 'STONE'
  - 'COBBLESTONE'
  - 'MOSSY_COBBLESTONE'
  - 'STONEBRICK'
  - 'LOG'
  - 'LOG2'
  - 'SANDSTONE'
  - 'GOLD_BLOCK'
  - 'GOLD_ORE'
  - 'GOLD_INGOT'
  - 'DIAMOND_BLOCK'
  - 'DIAMOND'
  - 'COAL_BLOCK'
  - 'COAL'
  - 'LAPIS_BLOCK'
  - 'INK_SACK'
  - 'IRON_BLOCK'
  - 'IRON_ORE'
  - 'IRON_IRON'
  - 'EMERALD_BLOCK'
  - 'EMERALD'
  - 'REDSTONE_BLOCK'
  - 'REDSTONE'

# Permission needed for fortune: ImmortalCustom.fortune

# Turn this to true if you want the list down below to be active
fortunelist: false

# The blocks on which fortune/smelt is active
# NOTE: You cannot disable blocks that fortune in vanilla
fortuneBlocks:
  - 'STONE'
  - 'COBBLESTONE'
  - 'MOSSY_COBBLESTONE'
  - 'STONEBRICK'
  - 'LOG'
  - 'LOG2'
  - 'SANDSTONE'
  - 'GOLD_BLOCK'
  - 'GOLD_ORE'
  - 'GOLD_INGOT'
  - 'DIAMOND_BLOCK'
  - 'DIAMOND'
  - 'COAL_BLOCK'
  - 'COAL'
  - 'LAPIS_BLOCK'
  - 'INK_SACK'
  - 'IRON_BLOCK'
  - 'IRON_ORE'
  - 'IRON_IRON'
  - 'EMERALD_BLOCK'
  - 'EMERALD'
  - 'REDSTONE_BLOCK'
  - 'REDSTONE'

# The display names for the minebow-related items
minebow:
  name: '&6MineBow &8(&e{ARROWS}&8)'
  arrow: '&eMineArrow'
  prefix: '&3[&6ImmortalCustom&3] '
  radius: 3

# The areas where ImmortalCustom is allowed
areas: {}

# Multipliers for each donator rank (or whatever you want)
# Permission would be: ImmortalCustom.multiplier.VIP
multipliers:
  VIP: 1.2
  MVP: 1.3
  Hero: 1.5
  Diamond: 1.8
  Bedrock: 2
  Owner: 5

# The different available backpack tiers.
# Permission for autopickup into backpacks: ImmortalCustom.backpack.autopickup
backpacks:
  start:
    title: '&7Fabric&fBackpack'
    size: 9
  epic:
    title: '&5Epic&fBackpack'
    size: 27
  master:
    title: '&6Master&fBackpack'
    size: 54

# Note that all the permissions can be wrote ImmortalCustom.[...] or ic.[...]